version: '3.8'

services:
  db:
    image: postgres:16
    container_name: proverdor_hp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proverdor_hp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_net

volumes:
  postgres_data:

networks:
  nest_net:
